"""
Pre-warm the local Parquet cache for a universe of tickers.

This is the "prepare the data" step for backtesting: download daily OHLCV once
into data/daily/, then let backtests read from disk (offline, fast, frozen).
Re-run with --refresh to top up only the bars since the last run.

The universe is a recipe, not data — universe.csv is checked in; the downloaded
Parquet files under data/ are git-ignored and regenerated by this script.

Run:
    venv/bin/python3 scripts/build_cache.py                 # from universe.csv
    venv/bin/python3 scripts/build_cache.py --refresh       # incremental top-up
    venv/bin/python3 scripts/build_cache.py --sp500         # full S&P 500
    venv/bin/python3 scripts/build_cache.py --tickers AAPL MSFT
"""
import argparse
import sys
from pathlib import Path

import pandas as pd

# make src/ importable when run as a standalone script
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from data_source import DailyDataCache  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_UNIVERSE = REPO_ROOT / "universe.csv"
SP500_CSV = (
    "https://raw.githubusercontent.com/datasets/"
    "s-and-p-500-companies/main/data/constituents.csv"
)


def read_universe_csv(path: Path) -> list[str]:
    df = pd.read_csv(path)
    if "symbol" not in df.columns:
        raise SystemExit(f"{path} must have a 'symbol' column")
    return df["symbol"].dropna().astype(str).str.strip().str.upper().tolist()


def sp500_tickers() -> list[str]:
    """Live S&P 500 constituents (yfinance uses '-' not '.', e.g. BRK-B)."""
    df = pd.read_csv(SP500_CSV)
    return df["Symbol"].astype(str).str.replace(".", "-", regex=False).tolist()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--universe", type=Path, default=DEFAULT_UNIVERSE,
                    help="CSV with a 'symbol' column (default: universe.csv)")
    ap.add_argument("--sp500", action="store_true",
                    help="use live S&P 500 constituents instead of the CSV")
    ap.add_argument("--tickers", nargs="+", metavar="SYM",
                    help="explicit tickers, overrides --universe/--sp500")
    ap.add_argument("--cache-dir", default="data/daily",
                    help="where to store Parquet files (default: data/daily)")
    ap.add_argument("--refresh", action="store_true",
                    help="incrementally top up already-cached tickers")
    ap.add_argument("--no-adjust", action="store_true",
                    help="store raw (unadjusted) OHLC instead of adjusted")
    args = ap.parse_args()

    if args.tickers:
        tickers = [t.upper() for t in args.tickers]
    elif args.sp500:
        tickers = sp500_tickers()
    else:
        tickers = read_universe_csv(args.universe)

    cache = DailyDataCache(cache_dir=args.cache_dir, auto_adjust=not args.no_adjust)
    print(f"Caching {len(tickers)} tickers -> {args.cache_dir} "
          f"(refresh={args.refresh}, adjusted={not args.no_adjust})")

    results = cache.bulk_download(tickers, refresh=args.refresh)

    ok = sorted(t for t, good in results.items() if good)
    failed = sorted(t for t, good in results.items() if not good)
    print(f"\nDone: {len(ok)} ok, {len(failed)} failed.")
    if failed:
        print("Failed:", ", ".join(failed))


if __name__ == "__main__":
    main()
